title: "[Idea] "
labels: ["idea"]
body:
  - type: markdown
    attributes:
      value: |
        Share your ideas for improving Nuxt UI Theme Builder!

  - type: textarea
    id: idea
    attributes:
      label: Your Idea
      description: Describe your idea or suggestion.
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: How would this idea benefit users?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Have you considered any alternatives or workarounds?
