title: "[Q&A] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Ask a question about using Nuxt UI Theme Builder.

        **Before asking:**
        - Check the [Help documentation](https://www.nuxt-ui-themes.com/help)
        - Search existing discussions

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any additional context that might help answer your question.
