import { describe, it, expect } from "vitest";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { LEARN_ROUTES, THEME_ROUTES } from "~~/shared/constants/routes";

// Share images are generated by scripts/generate-og-images.mjs and committed.
// Run `pnpm og:generate` after adding an article or preset.
const publicDir = resolve(__dirname, "../../../public");

describe("share images", () => {
  it.each([...LEARN_ROUTES, ...THEME_ROUTES])("exists for %s", (route) => {
    expect(existsSync(resolve(publicDir, `og${route}.png`))).toBe(true);
  });
});
